name: Crear APK de Lumina

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet y requisitos
        run: |
          pip install -r requirements.txt

      - name: Fabricar el APK
        run: yes | flet build apk

      - name: Subir APK para descargar
        uses: actions/upload-artifact@v4
        with:
          name: Lumina-App-Android
          path: build/apk/**/*.apk
